project:
  type: website
  output-dir: docs
website:
  page-footer: |
        © 2025, Татьяна Балтыжакова, Институт дизайна и урбанистики, Университет ИТМО
  sidebar:
    style: "docked"
    search: true
    logo: "images/logo.png"
    contents:
      - text: "О курсе"
        href: index.qmd
 #     - text: "Анализ точечных паттернов и кластеризация"
 #       href: 01-point-pattern-analysis.qmd
 #      - text: "Анализ размещения-распределения"
 #     href: 02-location-allocation.qmd
 #     - text: "Гравитационная модель Хаффа"
#        href: 03-gravity-model.qmd
 #     - section: "Пространственные веса и пространственная автокорреляция"
  #      contents: 
 #         - 04-spatial-weights.qmd
  #        - 05-spatial-autocorrelation.qmd
      - text: "Анализ рельефа"
        href: 01-relief.qmd
 #     - href: 08-online-mapping.qmd
      - section: "Работа с данными дистанционного зондирования"
        contents: 
          - 02-remote-sensing-data.qmd
          - 03-remote-sensing-basics.qmd
          - 04-vegetation-indices.qmd
    #      - 05-surface-temperature.qmd
      - text: "Литература"
        href: References.qmd
  navbar:
    left: 
      - text: "Курс лекций"
        href: Lectures.qmd
  #    - text: "Exam questions / Вопросы к экзамену"
  #      href: Exam.qmd
   #   - text: "Homework assignment / Домашнее задание"
  #      href: Homework.qmd
    right: 
      - href: https://t.me/geomess
        icon: telegram
      - icon: github
        href: https://github.com/baltti/spatial-analysis
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    shift-heading-level-by: 1
    anchor-sections: true
    link-external-icon: true

lang: ru-RU    
language: custom.yml

editor: visual

